import axiosWithAuth from "../../components/api/axiosWithAuth"

export const FETCH_CAMPAIGN_START = "FETCH_CAMPAIGN_START"
export const FETCH_CAMPAIGN_SUCCESS = "FETCH_CAMPAIGN_SUCCESS"
export const FETCH_CAMPAIGN_FAIL = "FETCH_CAMPAIGN_FAIL"

export const FETCH_SINGLE_CAMPAIGN_START = "FETCH_SINGLE_CAMPAIGN_START"
export const FETCH_SINGLE_CAMPAIGN_SUCCESS = "FETCH_SINGLE_CAMPAIGN_SUCCESS"
export const FETCH_SINGLE_CAMPAIGN_FAIL = "FETCH_SINGLE_CAMPAIGN_FAIL"

export const UPDATE_CAMPAIGN_START = "FETCH_CAMPAIGN_START"
export const UPDATE_CAMPAIGN_SUCCESS = "FETCH_CAMPAIGN_SUCCESS"
export const UPDATE_CAMPAIGN_FAIL = "FETCH_CAMPAIGN_FAIL"

// export const UPDATE_METRIC_START = "FETCH_CAMPAIGN_START"
// export const UPDATE_METRIC_SUCCESS = "FETCH_CAMPAIGN_SUCCESS"
// export const UPDATE_METRIC_FAIL = "FETCH_CAMPAIGN_FAIL"

export const ADD_METRIC_START = "ADD_METRIC_START"
export const ADD_METRIC_SUCCESS = "ADD_METRIC_SUCCESS"
export const ADD_METRIC_FAIL = "ADD_METRIC_FAIL"

export const FETCH_METRIC = "FETCH_METRIC"
export const DELETE_METRIC = "DELETE_METRIC"


